### ISSUE TITLE
王华州 的 2016 年记

### ISSUE THREAD

**Issue by huazhouwang** [winter-fall/YetAnotherDream#11]
> 2018 年我又会在哪里呢？

16 年发生了太多太多事情，我想如果不记下来的话就太对不起过去的一年了。

16 年，我大三。

自从 15 年上半年加入家创业团队被坑后下半年就一直呆在宿舍学习，期间最开始买了主席的 《Android 开发艺术探索》，真心很感激主席，更想不到没多久就见到了主席本人。然后还看各种博客，各种译文、原文，看完就整理、收藏到为知，慢慢的也快六百篇了，还没算一部分丢失的。后来加入了稀土掘金翻译组织，最开始了解掘金是在代码家博客上，便不断开始找组织，可惜申请实习的时候被拒了，掘金那边的 HR 姐姐还发短信安慰我，原本想好好保存的，可恨我一不开心就删东西的坏习惯......虽然实习申请没成功但后来还是加入它的翻译组织，在那里认识了挺多朋友，更重要的是现在看英语不用先在脑海里翻译成中文啦，哈哈。

在大三下半学期开学后听闻各大厂开招 17 年毕业生，便开始跃跃欲试，跟滨泓讨论了一段时间，最开始大家心里都没底，去找各大厂面试题做直接就懵逼了，但我一直都不缺少破罐子破摔的赌劲：理得了这么多，干了再说，最多就是被他们虐菜。便开始找内推投简历，这时不知哪来的勇气，竟然冒出了个念头，要不去找秋百万秋哥帮我内推阿里，哈哈，虽然秋哥早就离开阿里，但不试试怎么知道不行呢？秋哥也是爽快，在我还忐忑不安的时候就答应了!!对于秋哥，后面还有好多话要说。然后就直接跟内推人侯姐联系，侯姐也很爽快。没多久就接到了阿里的电面，我记得当时正在看书，突然有个杭州的电话，想想怎么这么多骗子，哎，玩玩也好。谁知那边开口就说：你好，请问你是王华州么？这边是阿里，请问你现在有空么？瞬间心都提到了嗓子眼，以前小时候总喜欢用这句，但这次是真真切切感受到了，我直接就不会说话了！！！还好之前学习东西挺扎实，虽然因为头脑空白有些没回答出来就直接问：抱歉，我看过，但我忘了，能否提醒下？那边也很 nice，整个过程四十多分钟。面完后我虚脱了......阿里的面试挺愉快，没多久就接到了 HR 的电话，然后就发 offer，就像在做梦一样。对了，还欠侯姐一顿饭呢，抱歉，我是个懒散的人，但我会记住的。

七月份加入了阿里的 AliExpress 团队。恩，就是那个 Android 端大胆采用了 Material Design 设计风格，又因为 AliExpress 是面向海外用户导致 Google Play 上一直有"国外的月亮还是比国内圆"恶意差评的团队。整个实习也挺愉快，虽然大家都说阿里的 HR 这不好那不好，但我觉得挺好的呀，我才来几天就请我们几个实习生吃饭啦。啊，吃很重要诶！！整个团队也挺照顾我，然后 Team Building 的时候就是他们玩，我吃。

后来我还记得秋哥发了个微博，就是这篇↓
![](http://oj360z136.bkt.clouddn.com/Screen%20Shot%202017-01-01%20at%201.42.50%20PM.png)
当我看到这篇微博时候就仿佛看到了跟秋哥一起撸代码的情景，此时不搏更待何时？又抱着试试的心理，就向秋哥自荐啦,嘻嘻......

然后阿里实习结束后没多久又飞往帝都，加入了秋哥的团队。地铁还是帝都的贴心，雾霾还是帝都的纯，只不过这些不是重点啦。每天六点多就早早起床跟阿展去赶地铁，晚上大概九点多回来，弄到零点才睡，但每周都有一个新的任务，一个不同的领域，嘿，特别是那种苦苦思索好久然后柳暗花明的感觉，你会很享受的。还有各种 LeetCode，对，我竟然迷上算法了。

这一年，去了好多地方，做了好多事，见了好多人，特别是秋哥，我想如果用四个字来概括的话，就是`知遇之恩`吧。

最后，我知道自己每次小小的进步都有一点小小的幸运在里面，也知道自己跟那些人比简直是地，更知道自己的要走的路还很长遇到的路口还很多，哎，没事，去试试嘛。恩，开心的事我写出来了，不开心睡一觉就好啦，哈哈。

**Comment by liaohuqiu** [comment]
非常感谢，感谢你们远道而来。
